
version: '3.4'
services: 
  demo: 
    image: romainplt/demo
    container_name: demo
    ports:
      - 8080:8080
    devices: 
      - /dev/isgx
    volumes:
      - demo:/tmp/demo:rw
    environment:
      - SCONE_LAS_ADDR=las
      - SCONE_CONFIG_ID=session_demo/demo      
      - SCONE_LOG=7
      - SCONE_MODE=hw
      - SCONE_HEAP=2G
      - SCONE_CAS_ADDR=cas
      - SCONE_ALPINE=1
      - SCONE_FORK=1
      - SCONE_SESSION_ID=session_demo
    networks:
      - romain-net
     
volumes:
  demo:
    external: true

networks:
  romain-net:
    external: true
