#!/bin/bash


########################################################################## VARIABLES #######################################################################

path_to_app=~/Documents/rest\ app/demo
name_app=demo
builder=gradle
dockerfile=Dockerfile-trusted
image_name=romainplt/demo
poids=1
taille=1


########################################################################## FUNCTIONS #######################################################################

usage()
{
	echo "  
	
	Run you app in a local CAS.
	
		./run_demo [-tag] 
		./run_demo -p ~/path/to/app/ -n my_app -b gradle	
		
		-p --path_to_app    Absolute path. You need to have a docker-compose in the folder you point. Default: ~/Documents/rest\ app/demo
		-n --name           Your app's name need to be the one you use to run docker-compose? Default: demo
		-b --builder        docker or gradle ? Default: gradle
		-d --dockerfile     Default: Dockerfile-trusted (only for docker)
		-i --image_name     Image name for building in docker. Default: romainplt/demo (only for docker)
		"
}	
	
	
remove_docker_containers()
{
	echo "Here are your current containers (not always running) : "
	yesorno=yes
	while [ $yesorno = yes ]; do
		docker ps -a --format "table {{.Image}}\t{{.Names}}\t{{.Status}}"
		echo " "
		echo "Do you want to stop/rm one or several ? (y/n)"
		read answer

		if [ $answer = y ] || [ $answer = yes ] || [ $answer = Y ]; then
			yesorno=yes
			echo "write 'all' if you want to remove them all. Or write one name."
			read container
			
			if [ $container = all ]; then
				echo "Removing all containers ..."
				docker stop $(docker ps -a -q)
		                docker rm $(docker ps -a -q)
		                yesorno=no
			else
				echo "removing container $container"
				docker stop $container 
				docker rm $container
				echo " "
			fi
		else 
			yesorno=no
		fi
	done
		
}


build_docker()
{ 

	echo " "
	echo "docker ..."
	if [ $(docker ps -qa -f name=demo) ]; then
		echo "Killing old app container ..."
		docker stop $name_app					
		docker rm $name_app
	fi
	echo "Building image ..."
	cd ~/Documents/rest\ app/demo
	rm dockerlogs.txt
	
	docker build --file $dockerfile --no-cache --build-arg JAR_FILE=build/libs/*.jar -t $image_name . >> dockerlogs.txt
	
	echo " "
	
	
}

build_gradle()
{
	echo " "
	echo "Gradle ..."
	echo "Killing old app container ..."
	if [ $(docker ps -qa -f name=demo) ]; then
		docker stop demo						
		docker rm demo
	fi


	echo "Building image ..."

	cd ~/Documents/rest\ app/demo

	./gradlew build buildImage
	echo " "
		
}

get_mr_enclave()
{
	cd ~/Documents/rest\ app/demo
	
	echo "Getting MrEnclave ..."
	mr_enclave=$(sed -n 17p dockerlogs.txt)
	echo "MrEnclave is : $mr_enclave"
	
	rm logs.txt
	sleep 1
	echo "Running demo ..."
	docker-compose up -d 
	sleep 10
	docker-compose logs >> logs.txt
	#cat logs.txt
	echo " "
	echo "Getting Enclave Hash when running ..."
	mr=$(cat logs.txt | grep Enclave)
	#echo "$mr"
	mr2=${mr#*:}
	#echo "$mr2"
	mr_compare=${mr2:1}
	echo "Enclave hash when running app is : $mr_compare"
	echo " "
	echo "Killing demo again"
	docker stop $name_app
	docker rm $name_app
	
}

mr_enclave_compare()
{
	if [ $mr_enclave = $mr_compare ]; then
		echo "Good news ! MrEnclaves are the same !"
	else
		echo "Ewwww ! Bad news, MrEnclaves don't match.
		Check your Dockerfile, maybe some parameters aren't the same than the ones the developper used."
	fi
		
}

create_session()
{
	cd ~/script

	#create session à partir du mr enclave et tout et tout
	echo " "
	echo "Creating session ..."

	sessionfile="session.yml"

	if [ -f "$sessionfile" ]; then
	        rm session.yml
	fi

	touch ~/script/session.yml

	echo "
name: session_demo
services:
  - name: demo
    image_name: romainplt/demo
    mrenclaves: [$mr_enclave]
    pwd: /
    environment:
      CLASSPATH: '/'
      SCONE_MODE: hw
      JAVA_TOOL_OPTIONS: '-Xmx256m'
      LD_LIBRARY_PATH: '/opt/scone/lib/'
      SECRET_POIDS: $poids
      SECRET_TAILLE: $taille" >> ~/script/session.yml

	cat ~/script/session.yml

}

attest_cas()
{
	echo " "
	source ~/script/start_cas -l -f ~/script/cas_las_scone/
}

push_session_to_cas()
{
	#push session to cas from sconecli image
	cd ~/script
	echo " "
	echo "Pushing session ..."
	rm sessionId.txt	
	docker exec -it scone sh -c "cd home && curl -k -s --cert conf/client.crt --key conf/client-key.key --data-binary @session.yml -X POST https://cas:8081/session" >> sessionId.txt
	session_id=$(cat sessionId.txt | grep hash)
	session_id=${session_id%*??}
	session_id=${session_id:11}
	echo "Session's id is : $session_id"
	
	rm sessionId.txt 
	
	echo $session_id >> sessionId.txt
	
	file="session.txt"	

	if [ -f "$file" ]; then
		rm session.txt 
	fi
	echo "Pushing session info in session.txt"
	docker exec -it scone sh -c "cd home && curl -k -s --cert conf/client.crt --key conf/client-key.key https://cas:8081/session/session_demo" >> session.txt
}

get_info()
{	
	cd ~/script
	
	echo " "
	echo "Getting Mr Enclave from session ..."
	
	hash1=$(cat session.yml | grep mrenclaves)
	hash2=${hash1:17}
	if [ "${hash2:0:1}" = "[" ]; then
		hash2=${hash2:1}
	fi
	hash3=${hash2%m*}
	hash4=${hash3%]*}
	echo "	MrEnclave got : $hash4"
	echo " "
}

verify_session_in_cas()
{

	echo " "
	cd ~/script
	echo "creating docker compose ..."
	
	rm docker-compose.yml
	
	touch docker-compose.yml
	echo "
version: '3.4'
services: 
  demo: 
    image: romainplt/demo
    container_name: demo
    ports:
      - 8080:8080
    devices: 
      - /dev/isgx
    environment:
      - SCONE_LAS_ADDR=las
      - SCONE_VERSION=1
      - SCONE_CONFIG_ID=session_demo/demo      
      - SCONE_LOG=7
      - SCONE_MODE=hw
      - SCONE_CAS_ADDR=cas
      - SCONE_HEAP=2G
      - SCONE_ALLOW_DLOPEN=1
      - LD_LIBRARY_PATH=/opt/scone/lib/
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - SCONE_ALPINE=1
      - SCONE_SESSION_ID=session_demo
      - POIDS=$poids
      - TAILLE=$taille
    privileged: true
    networks:
      - romain-net

networks:
  romain-net:
    external: true">>docker-compose.yml
      
      echo " "
      echo "Running $name_app"
      docker-compose up demo
      
      
}

################################################################### SCRIPT ##########################################################################

if [ "$1" == "" ]; then
	usage
	exit
fi

while [ "$1" != "" ]; do
	case $1 in
		-b | --builder )
			shift 
			builder=$1
			;;
		-a | --path_to_app )
			shift
			path_to_app=$1
			;;
		-n | --name )
			shift
			name_app=$1
			;;
		-d | --dockerfile )
			shift 
			dockerfile=$1
			;;
		-i | --image_name )
			shift
			image_name=$1
			;;
		-t | --taille )
			shift 
			taille=$1
			;;
		-p | --poids )
			shift
			poids=$1
			;;
		-h | --help )
			usage
			exit
			;;
		* ) 	usage
			exit
			;;
			
	esac
	shift
done

remove_docker_containers

case $builder in
	gradle | Gradle )
		build_gradle
		;;
	docker | Docker )
		build_docker
		;;
	* )	usage
		exit
		;;
esac


get_mr_enclave

sleep 1

mr_enclave_compare

sleep 3

create_session

attest_cas

push_session_to_cas

get_info

verify_session_in_cas

# c'est déjà bien
